### ISSUE TITLE
0 Werte bei jeder Aktualisierung?

### ISSUE THREAD

**Issue by DerOetzi** [Pix---/ioBroker.tankerkoenig#10]
Hallo,
 
ich habe seit einigen Tagen in iobroker die Historienfunktion in Verwendung inklusive Grafischer Darstellung. Unter anderem wollte ich die Spritpreise so als Verlauf darstellen. Leider habe ich gesehen, dass hier kein durchgängiger Graph sondern ein wildes Zick-Zack dargestellt wird. Nach kurzer Recherche habe ich folgendes herausgefunden. Der Adapter scheint bei jedem Durchlauf erstmal alle Werte auf 0 zu setzen bevor er die neuen Werte setzt wodurch z.B. folgende Historie ergibt.

1.13 | true | tankerkoenig.0 | 2017-11-15 01:30:03.184
0 | false | tankerkoenig.0 | 2017-11-15 01:30:03.168

Nun meine Frage was hier dahinter steckt, das zuerst die Nullung stattfindet und ob dies wirklich notwendig ist?

Danke

**Comment by DerOetzi** [comment]
Sorry habe gerade nochmal in die Config reingeschaut und gesehen, dass der Dialog bei mir leider sehr ungünstig abgeschnitten wurde. Haben den Haken jetzt rausgenommen ;) jetzt geht's.

Wenn ich es richtig verstehe geht es hier ja um Fehlerbehandlung? Könnte man da die Logik nicht dahingehend umbauen, dass das Nullen nicht immer sondern wirklich nur im Fehlerfall passiert, weil grundsätzlich halte ich es schon für sehr sinnvoll im Fehlerfall den Preis auf 0 zu setzen.

Danke

**Comment by Pix---** [comment]
Wenn der Haken gesetzt ist, wird der Wert vor jedem Schreibvorgang auf 0 gesetzt. Sollte nun nach einem Schreibvorgang ein Problem mit dem Abholen der Daten bestehen (zB kein Internet, Server tankerkoenig nicht erreichbar, Tankstelle schließt oder schaltet ab, dann bleibt nicht der letzte Preis dauerhaft stehen, sondern beim nächsten Intervall wird eine 0 geschrieben und danach wegen des Fehlers kein weiterer Wert. Sieht man nun zu einem späteren Zeitpunkt nach dem Preis de Tankstelle, wird man im Fehlerfall eine 0 finden und weiss so, dass etwas nicht stimmt. Ohne den Haken findet man den letzten aktuellen Preis, auch wenn der veraltet ist.
Standard sollte ohne Haken sein.

**Comment by thomasklein1975** [comment]
Hi,,

sorry, welche Harken muss ich wie setzen, damit nicht mit jeder Aktualisierung eine 0 geschrieben wird?

![grafik](https://user-images.githubusercontent.com/47893316/138321289-5ae8fd9c-ad0d-4f6b-9a9a-1eb47c1a87f8.png)

Hier die Werte:

![grafik](https://user-images.githubusercontent.com/47893316/138321401-ea700df4-bda8-428f-95fb-866761f8d293.png)
