### ISSUE TITLE
Öffnungszeiten der Tankstellen einbauen

### ISSUE THREAD

**Issue by Arnulf22** [Pix---/ioBroker.tankerkoenig#13]
Wie ich gesehen habe, bietet die API auch an, die Öffnungszeiten der Tankstellen abzurufen. Schön wäre es, diese Information auch über den Adapter im ioBroker zur Verfügung zu haben.
Dabei muss die Abfrage der Daten ja nicht so oft stattfinden, wie die Aktualisierung der Preise.

**Comment by Pix---** [comment]
Die Informationen über die Tankstelle werden von tankerkoenig.de als fertiges (kleines) Paket geschickt.  Die Öffnungszeiten gehören nicht dazu, sondern nur eine Info, ob die Station geöffnet ist oder nicht. 
Sollen die Zeiten übertragen werden, ist ein anderer Aufruf nötig, der deutlich mehr Daten vom Server zieht. Es gibt im ioBroker Forum ein Skript, das die Öffnungszeiten berücksichtigt. Für den Adapter ist das nicht allerdings geplant.

**Comment by Pix---** [comment]
Hier das Skript, welches auch die Öffnungszeiten einliest: http://forum.iobroker.net/viewtopic.php?f=21&t=1259#p10386
