### ISSUE TITLE
wiederkehrende Fehlermeldung

### ISSUE THREAD

**Issue by Marty56** [Pix---/ioBroker.tankerkoenig#15]
Ich bekomme bei meiner Tankstelle während der Nacht immer die Fehlermeldung

018-02-07 02:30:02.761 | error | Spritpreise einlesen (gezielte Stationen via ID) - Parse Fehler: TypeError: Cannot read property '1' of und
-- | -- | --

Es scheint, dass das Errorhandling des Json Parsers nicht richtig funktioniert.
Es wäre wünschenswert, wenn diese Fehlermeldung nicht kommen würde, weil der Nutzer keine Möglichkeit hat, Korrekturen durchzuführen.

Außerdem wäre es schön, wenn die Info, dass der Adapter gestartet wurde, nicht im Log File erscheint, wenn der Nutzer den Level Error für den Adapter eingestellt hat.

**Comment by Pix---** [comment]
Danke für die Hinweise.

Zum Fehler benötige ich mehr Daten. Ist die Station in der Nacht geschlossen? Ich versuche lieber, den Fehler zu eliminieren als nur das Fehler-Log zu unterdrücken.

Ich habe nun im Einstellungsfenster des Adapters einen weiteren Knopf zur Deaktivierung der Log-Einträge (bis auf error) eingestellt. Alle Logs vom Typ silly, info und debug werden nun unterdrückt. Type error wird weiterhin geloggt.

Der genannte Fehler kommt im try & catch auf den Befehl 
```
try {
    result=JSON.parse(body)
...

} catch (e) {
    writeLog("Spritpreise einlesen (gezielte Stationen via ID) - Parse Fehler: " + e, "error");
}
```
Der Fehler Code e wird also angehängt. 

Der oben genannte Fehler würde also weiterhin geloggt, auch wenn der Opt-out Haken gesetzt wurde. Meiner Meinung nach ist das korrekt, denn Fehler sollen ja auch geloggt werden. Ich könnte natürlich den Parse Fehler zukünftig im debug-Level loggen. Aber das ist nur eine Behandlung der Symptome.

Außerdem habe ich die Info-Logs über den Start des Adapters und das Einlesen der Werte nun auf debug gestellt.

 Bitte testen!

**Comment by Marty56** [comment]
Ja, die Station ist in der Nacht geschlossen.
Ich habe die GitHub Version installiert und teste.

Danke fürs Einbauen.

**Comment by Marty56** [comment]
Die Fehlermeldung scheint weg zu sein.
Was immer noch da ist, ist die ständig Info, dass Tankerkönig gestartet wurde.


host.raspberrypi | 2018-02-08 07:15:02.945 | info | instance system.adapter.tankerkoenig.0 terminated with code 0 (OK)
-- | -- | -- | --
host.raspberrypi | 2018-02-08 07:15:00.109 | info | instance system.adapter.tankerkoenig.0 started with pid 27190
host.raspberrypi | 2018-02-08 07:00:03.071 | info | instance system.adapter.tankerkoenig.0 terminated with code 0 (OK)
host.raspberrypi | 2018-02-08 07:00:00.074 | info | instance system.adapter.tankerkoenig.0 started with pid 26961
host.raspberrypi | 2018-02-08 06:45:03.200 | info | instance system.adapter.tankerkoenig.0 terminated with code 0 (OK)
host.raspberrypi | 2018-02-08 06:45:00.103 | info | instance system.adapter.tankerkoenig.0 started with pid 26747
host.raspberrypi | 2018-02-08 06:30:02.967 | info | instance system.adapter.tankerkoenig.0 terminated with code 0 (OK)
host.raspberrypi | 2018-02-08 06:30:00.112 | info | instance system.adapter.tankerkoenig.0 started with pid 26484
host.raspberrypi | 2018-02-08 06:15:02.825 | info | instance system.adapter.tankerkoenig.0 terminated with code 0 (OK)
host.raspberrypi | 2018-02-08 06:15:00.110 | info | instance system.adapter.tankerkoenig.0 started with pid 26158
host.raspberrypi | 2018-02-08 06:00:03.040 | info | instance system.adapter.tankerkoenig.0 terminated with code 0 (OK)
host.raspberrypi | 2018-02-08 06:00:00.101 | info | instance system.adapter.tankerkoenig.0 started with pid 25928
host.raspberrypi | 2018-02-08 05:45:02.888 | info | instance system.adapter.tankerkoenig.0 terminated with code 0 (OK)
host.raspberrypi | 2018-02-08 05:45:00.108 | info | instance system.adapter.tankerkoenig.0 started with pid 25709

**Comment by Pix---** [comment]
Diese Meldungen kommen vom Host (js-controller) und nicht vom Adapter. Darauf habe ich keinen EInfluss. Das liegt in der Natur der zeitgesteuerten Adapter. Sie starten und werden wieder beendet.

**Comment by Marty56** [comment]
Ok. Dann können wir den Issue schließen
