### ISSUE TITLE
Aktualisierung geht nicht

### ISSUE THREAD

**Issue by GuenWuen** [Pix---/ioBroker.tankerkoenig#19]
Ich habe im Admin Modus schon den Neustart der Instanz eingestellt.
Wird nicht aktualisiert.
Wenn ich manuell auf "Neu laden" klicken, werden die Kurse erneuert

**Comment by Pix---** [comment]
Was ist der Admin Modus? Welche Adapter Version?

**Comment by cbs** [comment]
Ich habe aktuell das gleiche Problem. Die Preise werden nicht aktualisiert. Laut Log wird der Adapter regelmäßig (hier alle 15 Minuten) gestartet:
`starting. Version 1.0.4 in /opt/iobroker/node_modules/iobroker.tankerkoenig, node: v8.11.2`
Wenn ich den Adapter allerding über ioBroker admin unter "Instanzen" anhalte und neu starte erscheint anschließend auch `objects written` im Log und die Preise wurden aktualisiert.

**Comment by BuZZy1337** [comment]
Welches schedule, also welche Uhrzeit hast du gesetzt zum aktualisieren? Versuch mal alle 7 Minuten und 39 Sekunden...

**Comment by Pix---** [comment]
Der Adapter wird derzeit für Admin3 vorbereitet. In diesem Zusammenhang werde ich den Code daraufhin überarbeiten, damit diese Probleme nicht mehr auftreten. 

Dennoch ist es weiterhin sinnvoll, den Adapter zu "krummen" Zeiten die Daten abrufen zu lassen, damit der Tankerkönig-Server nicht überlastet.

Ich bitte um Geduld.

**Comment by cbs** [comment]
Danke für den Tipp. Mit einer "krummen" Cron-Zeit läuft es jetzt recht zuverlässig.

@Pix--- Super, vielen Dank für die Info und die tolle Arbeit an dem Adapter!
