### ISSUE TITLE
Updating states twice (first with zero)

### ISSUE THREAD

**Issue by daniel-2k** [Pix---/ioBroker.tankerkoenig#20]
I have a trigger on a "feed" state to recognize changes of the price.
I noticed that the trigger is fired twice: the first time I get a value with 0 and shortly after the first trigger I receive a second trigger with the correct value.
That's a misbehaviour. I have to filter it in my trigger function but it would be better when the states are written correctly.

**Comment by Pix---** [comment]
That is not a misbehavior. It is a feature. As the readme/documentation says you can opt out writing 0 in adapter settings
