### ISSUE TITLE
Updatewunsch cheapest.xxx.stationid

### ISSUE THREAD

**Issue by xbow42** [Pix---/ioBroker.tankerkoenig#21]
Hallo,

erst mal danke für den tollen Adapter!

Auf meiner Vis-Startseite würde ich gerne die günstigte Tanke anzeigen.
Um das richtige Icon anzuzeigen würde ich gerne das widget "Image 8"-stateful verwenden. 
Bräuchte dazu aber die Nummer der Station um die richtige URL des Bildes zuzuordnen.
Ich würde mich freuen wenn der zusätzliche Datenpunkt bei jeder Spritsorte noch dazu kommt.
z.b. tankerkoenig.0.stations.cheapest.diesel.stationid

Gruß xbow42

**Comment by Pix---** [comment]
Hallo xbow42,
danke für die Anregung. Ich habe eine neue Version 1.2.0 erstellt, die jetzt neben dem Namen einer Station auch deren StationID speichert.
Ich musste eh die readme neu strukturieren und habe deine gute Idee gleich umgesetzt.

Bitte installiere direkt von hier aus Github und gib mir Feedback.

Gruß
Pix

**Comment by xbow42** [comment]
Hallo Pix,

das  ging ja fix, danke! Nur hatte ich mit das etwas anders gedacht.
sorry ID war wohl das falsche Stickwort, damit kann ich in VIS nichts anfangen.
Das widget "Image 8" wertet eine Zahl aus um den Index für das jeweilige Bild festzulegen.
Index müsste also die Zahl vom Datenkanal sein, die dann nach tankerkoenig.0.stations.cheapest.diesel.station_index geschrieben wird.
Bsp für meine 8 Stationen
tankerkoenig.0.stations.**0** ... tankerkoenig.0.stations.**7** müsste dann eine Zahl [**0-7**] nach
tankerkoenig.0.stations.cheapest.SPRITSORTE.station_index geschrieben werden.

Dann ist mir gerade noch etwas aufgefallen:
in tankerkoenig.0.stations.cheapest.diesel.status steht jetzt nicht mehr "open" oder "closed" sondern der Wert der station_id. Somit hat es leider meine geöffnet/geschlossen-Anzeige im VIS zerschossen.

Gruß xbow42

**Comment by Pix---** [comment]
Hallo,
ich habe den Fehler `station_id` in `status` jetzt behoben. Neue Version 1.2.1

Zum ersten Punkt:
So wie du es beschreibst, möchte ich es nicht lösen. Der Umbau wäre zu sehr der Nutzung des `image-8-stateful` Widgets geschuldet. Da kann man jetzt auch ein separates Javascript bauen, das einfach den `tankerkoenig.0.stations.cheapest.diesel.station_id` überwacht und den entsprechenden Link zur Grafik in einen neuen Datenpunkt schreibt. Den Datenpunkt kannst du per vis-binding in die View einbauen.
Da ich den Adapter für material anpassen muss, kann ich bei der Gelegenheit natürlich auch gleich weitere Funktionen einbauen, die allen Nutzern helfen. Ich müsste mich nur zum einen oder anderen Thema erst schlau machen.

Ideen:

- zu jeder Station manuell auszufüllende Felder mit Geodaten zufügen. Die könnten später in VIS verwendet werden
- o.g. Felder ggf. durch eine innerhalb der Einstellungen manuelle ausgelöste Abfrage der Tankerkönig `detail.php` mit weiteren Inforamtionen füllen, die über die standardmäßig vom Adapter genutzte Abfrage nicht kommen. Diese brauchen ja nur für die Einrichtung einmal vom tankerkönig - Server geladen werden.
- zu jeder Station ein Feld für ein Logo
- eine frei definierbare Pausenzeit, in der keine Abfragen gemacht werden
- Zufallsgenerator für die Startminute zwischen 1 und 4 bei Adapterstart (`schedule("1 * * * *")`)

Allerdings sollte klar sein, dass mehr Funktionen auch erstmal eine längere Bauzeit brauchen. 

Gruß
Pix

**Comment by xbow42** [comment]
Hallo Pix,
wieder schnell repariert super!
Ich bin da leider noch nicht fit in iobroker und der Javascriptsyntax, darum hab mal mit Bockly was zusammen geschuppst.
![tanker_blockly](https://user-images.githubusercontent.com/44160574/49045525-8ebcd900-f1d1-11e8-98be-b3ced902fa9c.png)
Es scheibt aber keinen Block zu geben wo ich meinen "Objektname"-string als ObjektID einklicken kann.
Code Kopiert und in Javascript eingefügt dann so:
`var objektname, i;

// Dieseltanken abklappern und Index finden
on({id: "tankerkoenig.0.stations.cheapest.diesel.station_id", change: "ne"}, function (obj) {
  //var value = obj.state.val;  //erschießt sich mir nicht für was ich die variablen brauchen sollte
  //var oldValue = obj.oldState.val; //...wenn keine Fehler kommen löschen
  for (i = 0; i <= 7; i++) {
    objektname = ['tankerkoenig.0.stations.',('' + i),'.station_id'].join('');
    if (getState("tankerkoenig.0.stations.cheapest.diesel.station_id").val == getState(objektname).val) {
      setState("tankerkoenig.0.stations.cheapest.diesel.station_index", i); 
     //Datenpunkt vorher manuell erstellt
      break;
    }
  }
});`
Das mit dem "Datenpunkt kannst du per vis-binding in die View einbauen" habe ich nicht kapiert.
vermutlich geht das alles viel einfacher als ich das mit dem station_index und dem Image8-widget umsetze. Vielleicht baust du in die Doku mal ein Beispiel ein.

bez Doku: da muss es heißen
"Ausserdem werden noch DREI Datenpunkte gespeichert:"

Tolle Ideen hast du da hast.
Aktuell wüsste ich nicht was ich mit den Geodaten in Vis anstellen sollte.
zu "eine frei definierbare Pausenzeit, in der keine Abfragen gemacht werden"
Wie wäre es mit einem boolenDatenpunkt( den man von seiner Homesteuerung setzen kann) der an gibt ob die Spritpreise abgerufen werden sollen oder eben nicht.
Mögliche Trigger für den Datenpunkt könnte dann sein An/Abwesenheit;Tag/Nachmodus;Vis-Zugriff(wobei ich nicht weiß ob/wie man das irgenwie erfassen kann). 
Wobei, wenn man die Spritpreise für Flotanzeige aufzeichnet will man ja alle Werte sehen...
Für sowas wäre eine rrd-Datenbank am besten damit man mal nach ein paar Jahren sehen kann wie sich der Spritpreis gesteigert haben ohne 1million-Daten zu haben.

es braucht alles seine Zeit und Ideen müssen reifen.
Gruß xbow42

**Comment by Pix---** [comment]
Hallo,

danke für den Hinweis für die Readme. Ist erledigt.

Nun zu deinem Problem. Der ganze Aufwand, das Icon abhängig von der Position der Station im Einstellungsbereich zu machen, ist ja wieder zunichte, wenn man eine andere Station an die Position schreibt oder ähnlich.

Du solltest das Icon davon abhängig machen, was tatsächlich für eine Station gerade gezeigt wird bzw. im Datenpunkt steht. Das geht meistens ganz gut mit dem Namen, da man ja sowas wie "ARAL Bahnhofstraße" oder "ESSO Minidorf" im Namen hat. Man kann den Namen ja selbst vergeben.
Du müsstest dann ein Objekt anlegen, das passend zum Namen den richtigen Pfad zum Icon ausgibt.

Neues Javascript:
```
createState("TankerkoenigCheapestIconHTML", "");
var icons = {
    Name1 : "<img src=\"pfad/zum/icon/station1\">",
    Name2 : "<img src=\"pfad/zum/icon/station2\">",
    Name3 : "<img src=\"pfad/zum/icon/station3\">",
    Name4 : "<img src=\"pfad/zum/icon/station4\">",
}
on("tankerkoenig.0.stations.cheapest.diesel.name", function(obj) {
    setState(idNeuerDatenpunkt, icons[obj.state.val]);
});
```
Damit erhält der neue Datenpunkt immer den Pfad zum Logo der aktuell billigsten Tankstelle.

Es ist vielleicht wirklich einfacher, wenn ich in einer zukünftigen Version den User auch Pfade zum Icon jeder Station hinterlegen lasse.
