### ISSUE TITLE
Billigste Tanke, Preis passt nicht

### ISSUE THREAD

**Issue by xbow42** [Pix---/ioBroker.tankerkoenig#23]
Hallo Pix,

ist mir heute morgen in Vis aufgefallen, da der Preis(billigste Tankstelle) auf meiner Startseite nicht mit dem Preis in der Übersicht(alle Tankstellen) übereinstimmt.
![tankerkoenig](https://user-images.githubusercontent.com/44160574/49338813-9d6b1c00-f627-11e8-97da-bf6f70fe97a0.png)

**Comment by Pix---** [comment]
Ich konnte den Fehler noch nicht reproduzieren. Vielleicht kannst du den Preis von `cheapest`auch noch loggen und dann mal prüfen, ob es häufiger Abweichungen gibt.

Gruß
Pix

**Comment by Pix---** [comment]
Sorry, wollte nicht schließen.

**Comment by Zwer2k** [comment]
Hallo,
Fehler sollte mit meinem pull request behoben sein. Die Anfrage habe ich vor einem Monat gestartet, wurde leider noch nicht übernommen.
[https://github.com/Pix---/ioBroker.tankerkoenig/pull/34](https://github.com/Pix---/ioBroker.tankerkoenig/pull/34)

**Comment by Pix---** [comment]
Merged!
