### ISSUE TITLE
request wird nicht ausgeführt

### ISSUE THREAD

**Issue by arteck** [Pix---/ioBroker.tankerkoenig#26]
der `request(url, function (error, response, body) { `wird bei Aktualisierung nicht ausgeführt
es ist so als ob dieser bei Adapterstart nicht beendet wurd .. und der nächste mag nicht anlaufen..

wenn der Adapter neu gestartet wird gehts..

Vorschlag: bau den um auf interne Verarbeitung in der Schleife.. dann endet der request auch.

**Comment by arteck** [comment]
schau dir meinen HS100 Adapter an ...

**Comment by arteck** [comment]
hier der rahmen ist schon da.. und funktioniert .. alle 15 min
https://github.com/arteck/ioBroker.tankerkoenig
admin musst du noch .. am besten direkt nach admin3

**Comment by Pix---** [comment]
Hallo arteck,

vielen Dank für die Initiative. Baue gerade einen Einbauschrank und habe wenig Zeit. Sehe es mir an! Admin 3 steht schon lange auf der Liste.

Pix

Am 23.01.2019 um 21:41 schrieb arteck <notifications@github.com<mailto:notifications@github.com>>:


hier der rahmen ist schon da.. und funktioniert .. alle 15 min
https://github.com/arteck/ioBroker.tankerkoenig
admin musst du noch .. am besten direkt nach admin3

**Comment by Pix---** [comment]
Habe deinen "Rahmen" übernommen. Läuft seit ein paar Tagen durch bei mir. Danke
