### ISSUE TITLE
Millionen Requests, Software ist defekt

### ISSUE THREAD

**Issue by tankerkoenig** [Pix---/ioBroker.tankerkoenig#29]
Hallo, seit einigen Stunden kommen hunderte Requests/Sekunde auf das Tankerkönig-API von mehreren Usern, die wahrscheinlich diese Software einsetzen. Bitte die Änderung wieder zurücknehmen, sonst müssen wir unseren API-Server vom Netz nehmen. Es wäre schön, wenn im Request-Header eine Info über die Software (incl Version) mitgeschickt würde, dann können wir besser reagieren.

**Comment by Pix---** [comment]
Der Fehler ist mit Version 2.0.4 behoben. Er tauchte von 2.0.0 bis 2.0.3 auf. Bisher ist für die Masse der Nutzer im stable Repository noch nur die Version 1.0.4 nutzbar. Wir sollten beobachten, ob in den nächsten Tagen Probleme auftauchen.

**Comment by tankerkoenig** [comment]
Also heute abend kommen noch wesentlich mehr Requests als gestern rein (seit 15:30 Uhr ca 5 Mio), der Fehler scheint nicht behoben, bitte fixen, sonst müssen wir den Server abschalten. Kann es sein, dass sich Leute eine alte, kaputte Vesrion installieren, nicht die neue gefixte - falls sie wirklich gefixt ist? Ein Request-Header mit Software und Version wäre sehr nützlich, dann können wir bei solchen fehlern gezielt die kaputte Version abklemmen und unschuldige müssten nicht so leiden..

**Comment by DevilDesire** [comment]
ich habe die Version 2.0.4 installiert

![grafik](https://user-images.githubusercontent.com/13473894/53193955-934b2f00-3612-11e9-9e1b-58e000e104d7.png)

**Comment by ThmsD** [comment]
Hier ebenfalls Probleme.
Bemerkt habe ich diese nach der Installation von Version 2.0.4 (vorher ist mir nichts aufgefallen).
![image](https://user-images.githubusercontent.com/11979724/53205633-209c7c80-362f-11e9-9470-a192f79b468d.png)

**Comment by tankerkoenig** [comment]
Das "connection refused" kommt von einer Blockade, die jetzt im Server greift, wenn für 60 Sekunden mehr als 1 Request/Sekunde kommt. Die Blockade für diese IP-Adresse wird nach einer Stunde automatisch aufgehoben: also abwarten, bis eine gefixte Version der Software kommt, diese einspielen und nach einer Stunde sollte es wieder gehen..

**Comment by ThmsD** [comment]
Nach dem Update auf 2.0.4 führte der Adapter sehr viele Anfragen in kurzer Zeit aus. Das konnte ich anscheinend beheben, indem ich in den Instanzeinstellungen das Intervall neu gesetzt habe.

**Comment by jens-maus** [comment]
Auch ich kann bestätigen das mit der 2.0.4 das Problem nicht behoben war/ist. Bei mir war es sogar so, das das aktivieren der 2.0.4 version die gesamte Internetverbindung lahmlegte...

**Comment by ThmsD** [comment]
Hier nochmal ein Screenshot davon, wie mein Log aussah, als ich auf 2.0.4 geupdated habe.
Wie bereits erwähnt, nach Änderung des Intervalls in der Instanz wurden die vielen Abfragen gestoppt.
![image](https://user-images.githubusercontent.com/11979724/53232650-d1d10000-368b-11e9-98b4-34145782a8a9.png)

**Comment by jens-maus** [comment]
Hab mir mal erlaubt das Problem zu reparieren und hab den folgenden pull request erstellt:

https://github.com/Pix---/ioBroker.tankerkoenig/pull/30

Zusätzlich sollte damit nun der adapter auch einen `User-Agent:` request header mitliefern sodass Tankerkönig auf zukünftige Probleme mit dem adapter entsprechend reagieren kann.

**Comment by Pix---** [comment]
Vielen Dank dafür! Sobald die Tests von Travis und Appveyor abgeschlossen sind, werde ich mergen.
👍

**Comment by jens-maus** [comment]
@tankerkoenig Bitte dann sobald die 2.0.5 draussen ist eventuelle IP-Sperrungen wieder aufheben. Das Problem sollte ja nun behoben sein.

**Comment by stoamandl** [comment]
> @tankerkoenig Bitte dann sobald die 2.0.5 draussen ist eventuelle IP-Sperrungen wieder aufheben. Das Problem sollte ja nun behoben sein.

Ich kann leider nicht bestätigen das der Fehler mit 2.0.5 behoben ist.
Habe soeben das Update dahin gemacht. Mit dem gleichen Effekt.
Erst als ich die Intervall Zeit geändert habe, hörten die Anfragen auf.

**Comment by tankerkoenig** [comment]
Problem ist mit der 2.0.5 NICHT behoben, wir sehen immer noch hunderte Requests/Sekunde, jetzt mit dem User-Agent-Header "iobroker.tankerkoenig/2.0.5".

**Comment by ThmsD** [comment]
Noch eine Sachen, die ich so bisher beim Adapter nicht gesehen habe (bzw. mir bisher evtl. nicht aufgefallen ist):
Warnings, dass die Instanz bereits läuft.
![image](https://user-images.githubusercontent.com/11979724/53301696-5a9b9780-3856-11e9-8439-cdf95f98f55c.png)

**Comment by Ilovegym66** [comment]
@ThmsD das bedeutet, du hast die Instanz wahrscheinlich 2x laufen, wurde einmal nicht richtig beendet. mit "ps -A | grep io" bekommst du alle laufenden iobroker Instanzen angezeigt, wenn du also iobroker beendest mit "iobroker stop" einen Moment wartest, und dann "ps -A | grep io" eingibst, sollten keine prozesse mehr mit io.xxxx angezeigt werden. Wenn doch, dann mit "kill prozessnr." beenden. Dann iobroker neu starten, und der Fehler kommt nicht mehr.
