### ISSUE TITLE
Einstellungen können nicht gespeichert werden

### ISSUE THREAD

**Issue by der-eine** [Pix---/ioBroker.tankerkoenig#31]
Hallo zusammen,

habe den Adapter mehrfach neu installiert jetzt auch über Github 2.0.5.
Kann die Einstellungen nicht speichern. 
API Key und Tankstellen werden mit "good" betitelt.

Woran kann das liegen?
Danke schon mal

**Comment by Pix---** [comment]
Hallo,

hast du den alten Adapter gelöscht, bevor du den neuen installiert hast? Also den adapter, nicht nur die Instanz. 

Welchen Browser in welchem Betriebssystem nutzt du?

Hat dein API Schlüssel das Format 6Zeichen-4Zeichen-4Zeichen-4Zeichen-12Zeichen ?

Gibt es eine Logausgabe?

**Comment by der-eine** [comment]
Hallo Pix,

danke für die schnelle Antwort. Habe den Adapter und Instanz gelöscht über GitHub neu installiert und einen Upload gemacht.

Safari auf OSX 10.14.2
8-4-4-4-12

`

  |   |   |  
-- | -- | -- | --
  |   |   |  
  |   |   |  
  |   |   |  
  |   |   |  
  |   |   |  
  |   |   |  

`

**Comment by itsolon** [comment]
Hallo,
hatte an Tankerkönig geschrieben weil ich das Problem auch hatte.
Die haben gesagt das liegt nicht an Tankerkönig, sondern vielmehr an der iobroker app.
ich habe alles installiert und versucht 1.0.4 2.0.5 und so weiter ich konnte einfach nicht speichern.
und wisst ihr was es dann letztendlich war?
ich hatte beim Abfrageintervall nichts drinnenstehen, also ich hatte es noch nicht gesetzt.
die wollen mind. 5 Minuten ich habe jetzt einfach 15 Minuten eingestellt, da ich den Service von Tankerkönig nicht unnötig belasten möchte.
einfach eine Zeit eintragen und schön könnt Ihr speichern!

Vielen Dank nochmal an Tankerkönig und auch an den Author der APP der sich die Mühe gemacht hat und das ding geschrieben hat.

**Comment by Pix---** [comment]
@itsolon Danke für das Feedback. Es ist richtig, dass die Adaptereinstellungen nur gespeichert werden, wenn ein Intervall und ein API-Key gesetzt wurden und die Tankstellen ID im korrekten Format eingegeben wurden. Die Prüfung, ob ein Intervall gesetzt wurde könnte man ggf. wieder entfernen, da im Adapter später eh geprüft wird, ob mindestens 5min gesetzt wurden.

@der-eine Die Logausgabe sagt aus, dass du genau dieses Problem hattest. 
```Sync time was too short (undefined). New sync time is 5 min```

**Comment by der-eine** [comment]
@pix--- Danke für die Info! Jetzt läuft er wieder. 👍🏻
