### ISSUE TITLE
Autogas LPG ?

### ISSUE THREAD

**Issue by bug84** [Pix---/ioBroker.tankerkoenig#39]
Halo, gibt es eine Möglichkeit ,Autogas einzubinden?

**Comment by Pix---** [comment]
Hallo, nein - der Adapter liefert nur die Informationen, die von Tankerkönig bereitgestellt werden. Das sind derzeit Diesel, Super und E10. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bug84** [comment]
Ok und dieser Ansatz?
Scheint ja schon fertig geschrieben, nur die Einbindung zu IoBroker müsste man noch fertig machen?

https://github.com/vlcty/check_clever_tanken

**Comment by Pix---** [comment]
Dieser Ansatz basiert auf dem Parsen der Webseite. Wie der Autor schreibt, ist die Funktion davon abhängig, dass sich die Seite nicht ändert.
Du kannst die Daten der Seite auch mit dem Parser Adapter extrahieren. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bug84** [comment]
Ja das wäre doch schon mal eine super Lösung. In der Hoffnung, das sich das Layout nicht ändert.

Da ich kein Profi bin, sogar wahrscheinlich nicht mal als JavaScript Amateur durchgehe:
Könntest du bitte den Weg mit dem Parser Adapter näher beschreiben?

Vielen Dank

**Comment by Pix---** [comment]
Stell dir Frage bitte im ioBroker Forum. 
Hier sind die Issues des Tankerkönig Adapters. 

Gruß
Pix

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bug84** [comment]
Danke. Hab’s mit dem parser hinbekommen, super 👍
