### ISSUE TITLE
Update stable version in repo to 2.0.6

### ISSUE THREAD

**Issue by GermanBluefox** [Pix---/ioBroker.tankerkoenig#44]
# Think about update stable version to 2.0.6
**Version**: stable=**2.0.5** (375 days old) => latest=**2.0.6** (322 days old)
**Installs**: stable=**2634** (51.28%), latest=**2124** (41.35%), total=**5137**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1291)

**Comment by Pix---** [comment]
Done
