### ISSUE TITLE
update stable repo?

### ISSUE THREAD

**Issue by Apollon77** [Pix---/ioBroker.tankerkoenig#5]
Hey,

Stable Repo still has v1.0.0. When still the most stable version, everything great, if not please update in stable-repo.

(see https://github.com/ioBroker/ioBroker.repositories)

Thanx for checking

Ingo F

**Comment by Apollon77** [comment]
?! :-)

**Comment by Pix---** [comment]
Hallo Ingo,

der Adapter hat auf npm Version1.0.4 und im Stable nur 1.0
Wie kann ich das ändern?

Gruß
Jens

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.repositories forken, dann den updatebefehl (siehe README dort) ausführen und dann PR einreichen

Ingo
