### ISSUE TITLE
Spritpreise einlesen schlägt fehl

### ISSUE THREAD

**Issue by Farmer-cb** [Pix---/ioBroker.tankerkoenig#51]
Hallo
Bei mir kommt immer der Fehler
`27159) Spritpreise einlesen (gezielte Stationen via ID) - Fehler: Error: getaddrinfo EAI_AGAIN creativecommons.tankerkoenig.de creativecommons.tankerkoenig.de:443
`
egal welche Tankstelle ich eingebe, 
bei einem anderen iobroker projekt (Freund) funktioniert es 
habe die Instance schon gelöscht und neu installiert, egal welche Version ich nehme (V2.0.5 oder v2.0.9)
habe auch schon eine API-Key von einem Freund genutzt bei dem es funktioniert

im log (/opt/iobroker/log/iobroker.current.log) steht auch nicht mehr.
wenn ich den API-Key und die Tankstellen id im Browser eingebe kommen plausible daten

https://creativecommons.tankerkoenig.de/json/detail.php?apikey=xxxxxxxxx-yyyyy-7ab0-92c1-18f71e80f640&id=32c47dff-4bf0-4f51-928a-8e113c28608a
Ergebnis
`{"ok":true,"license":"CC BY 4.0 -  https:\/\/creativecommons.tankerkoenig.de","data":"MTS-K","status":"ok","station":{"id":"32c47dff-4bf0-4f51-928a-8e113c28608a","name":"Tank Plus Tankstelle","brand":"Tank Plus","street":"Nordgaustra\u00dfe","houseNumber":"36","postCode":93059,"place":"Regensburg","openingTimes":[],"overrides":[],"wholeDay":true,"isOpen":true,"e5":1.219,"e10":1.169,"diesel":1.009,"lat":49.037666,"lng":12.104853,"state":null}}`

sollte also nicht am PAI oder Tankstellen-ID liegen

meine Machine:
Platform: **linux**
Betriebssystem: **linux**
Architektur: **x64**
CPUs: **4**
Geschwindigkeit: **2586 MHz**
Modell: **Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz**
RAM: **7.17 GB**
System Betriebszeit: **5 T. 21:02:29**
Node.js: **v10.16.3 (Es gibt eine neuere Version: v10.23.0 - Empfohlene Version v12.19.0)**
NPM: **6.9.0**
Festplatte Größe: **7.81 GB**
Festplatte frei: **4.04 GB**
Anzahl der Adapter: **309**
Betriebszeit: **5 T. 21: 01:19**
Aktive Instanzen: **20**
Hostname: **iobroker**

**Comment by Pix---** [comment]
Hallo,
danke für die Meldung.
Da du deinen API Key natürlich nicht hier veröffentlichen kannst, kann ich nicht überprüfen, ob es nicht doch am Schlüssel liegt. Ich bekomme jedenfalls auch ein brauchbares Ergebnis, wenn ich deinen Link mit meinem Schlüssel verwende.

Hast du im Forum mal nach dem Fehler gesucht. Ich habe diesen Eintrag gefunden, vielleicht hilft er weiter:
[https://forum.iobroker.net/topic/6098/gelöst-error-getaddrinfo-eai_again](https://forum.iobroker.net/topic/6098/gelöst-error-getaddrinfo-eai_again)

Fragst du noch andere Daten aus dem Internet ab? Gibt es da auch Probleme?

Gruß
Pix

**Comment by Farmer-cb** [comment]
Hallo
Danke für den Stups indie richtige richtung, habe zwar auch bei google gesucht, aber leider nicht das richtige gefunden.
habe jetzt mal einen anderen DNS-Server eingetragen und siehe da, es funktioniert

Danke
