### ISSUE TITLE
report information according LOG entry 

### ISSUE THREAD

**Issue by Seqway** [Pix---/ioBroker.tankerkoenig#55]
Hello,

while starting tankerkoenig on my new system i get a message that i should report something to the developer. Herewith i do it:

The message is in the LOGs:
`

tankerkoenig.0 | 2021-01-03 12:31:42.612 | warn | (18592) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
tankerkoenig.0 | 2021-01-03 12:31:42.612 | warn | (18592) Object tankerkoenig.0.tank is invalid: obj.type has to exist

`

**Comment by Pix---** [comment]
Probably same issue [here](https://github.com/Pix---/ioBroker.tankerkoenig/issues/56#issuecomment-765574704)

**Comment by Diginix** [comment]
I have still this bug with v2.1.1

> 2021-12-01 20:00:51.223 - warn: tankerkoenig.0 (1179154) Object tankerkoenig.0.tank is invalid: obj.type has to exist
> 2021-12-01 20:00:51.223 - warn: tankerkoenig.0 (1179154) This object will not be created in future versions. Please report this to the developer.
