### ISSUE TITLE
Warnung "has no existing object," beim Beta-Test von js-controller 3.2.x

### ISSUE THREAD

**Issue by Feuer-sturm** [Pix---/ioBroker.tankerkoenig#56]
Beim Beta-Test von js-controller 3.2.4 kommt folgene Warnung:
```
tankerkoenig.0 | 2021-01-09 22:52:46.840 | warn | (3413) State "tankerkoenig.0.stations.8.e10.combined" has no existing object, this might lead to an error in future versions
```

Verwendete Version von tankerkoening: 2.0.9

**Comment by Nunmalfix** [comment]
Die Warnungen kommen auch mit der js-controller version 3.2.7 aus dem latest:
warn: tankerkoenig.0 (18571) State "tankerkoenig.0.stations.8.e10.combined" has no existing object, this might lead to an error in future versions

**Comment by winnyschuster** [comment]
Der Fehler liegt [hier](https://github.com/Pix---/ioBroker.tankerkoenig/blob/master/io-package.json#L2192)

**Comment by Pix---** [comment]
Danke für die Fehlersuche. @winnyschuster hat Recht, der Datenpunkt "tankerkoenig.0.stations.8.e10.combined" existiert nicht, da ich beim Anlegen einen Tippfehler gemacht habe (0 statt 8). Ist mir nie aufgefallen, da ich nicht so viele Stationen abfrage.
Ich versuche, es heute oder morgen zu fixen.

**Comment by Nunmalfix** [comment]
Komisch ist aber, wenn ich die 0 durch eine 8 ersetze und den Adapter neu starte dann kommt halt jetzt das:

State "tankerkoenig.0.stations.8.e10.combined" has no existing object, this might lead to an error in future versions

**Comment by Nunmalfix** [comment]
OK wenn man den Datenpunkt combined in der Station 8 selbst anlegt, dann ist der Fehler weg. Anscheinend werden die Datenpunkte nur initial angelegt und dann nicht mehr.

**Comment by Pix---** [comment]
Hallo,
schaffe es heute nicht mehr, wollte aber noch kurz antworten.
Wenn du auf deiner Installation den Code änderst reicht ein Neustart nicht. Du musst auch einen Upload machen.
Und ja, die Datenpunkte werden nur initial angelegt. Etwas, das ich schon lange ändern will.
ifnotexist ist das das Stichwort, oder?

**Comment by Nunmalfix** [comment]
Alles gut, ich hatte den Datenpunkt kurzerhand manuell angelegt und dann war Ruhe. Also keine Eile ;-)

**Comment by crunchip77** [comment]
möchte noch hinzufügen das folgende Meldung noch mit auftaucht und veraltet ist
`tankerkoenig.0	2021-01-23 13:47:46.387	warn	(15196) Please update js-controller to at least 1.2.0`

**Comment by ChrisWoehrle** [comment]
Ich habe das Problem"hart" gelöst. Alle E10 Ordner gelöscht 😉

**Comment by SmartHomie1** [comment]
Hi,
ich bekomme auch oben genannten Warnhinweis (29652) State "tankerkoenig.0.stations.8.e10.combined" has no existing object, this might lead to an error in future versions). 
Da ich kein Linux Guru bin.....wird der Bug bei einer nächsten Version im Stable Modus verschwunden sein? Ich nutze momentan Adapter Version 2.0.6 und JS Controller 3.2.16.
Danke für ein kurzes Feedback

Roland
