### ISSUE TITLE
Preis für Super Plus

### ISSUE THREAD

**Issue by PeKu64** [Pix---/ioBroker.tankerkoenig#59]
Leider fehlt der Super Plus Preis.
Wäre schön, wenn der auch mit abgefragt werden könnte.

**Comment by Pix---** [comment]
Der Adapter fragt keine Preise ab, sondern schreibt die von Tankerkoenig.de gelieferten Informationen in entsprechende Datenpunkte. 
Es gibt Diesel (B12), E5 und E10. Details gibt es [hier](https://creativecommons.tankerkoenig.de)
