### ISSUE TITLE
JS-Controller 3.3 - wrong type "number" but has to be "string"

### ISSUE THREAD

**Issue by TheBrain26** [Pix---/ioBroker.tankerkoenig#61]
tankerkoenig.0 | warn | Read-only state "tankerkoenig.0.stations.8.e5.feed" has been written without ack-flag with value "0"
tankerkoenig.0 | warn | Read-only state "tankerkoenig.0.stations.8.status" has been written without ack-flag with value ""
tankerkoenig.0 | warn | Read-only state "tankerkoenig.0.stations.7.diesel.3rd" has been written without ack-flag with value "0"
tankerkoenig.0 | warn | State value to set for "tankerkoenig.0.stations.7.diesel.short" has wrong type "number" but has to be "string"
tankerkoenig.0 |warn | Read-only state "tankerkoenig.0.stations.7.diesel.combined" has been written without ack-flag with value ""
ioBroker/ioBroker.js-controller#1299

**Comment by Azathoth88** [comment]
Ich habe das selbige Problem. Bitte um zeitnahen fix.

**Comment by OlfrygtACAB** [comment]
tankerkoenig.0 | 2021-05-01 07:20:25.168 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.diesel.short" has been written without ack-flag with value "0"
-- | -- | -- | --
tankerkoenig.0 | 2021-05-01 07:20:25.168 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.diesel.feed" has been written without ack-flag with value "0"
tankerkoenig.0 | 2021-05-01 07:20:25.167 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.e10.combined" has been written without ack-flag with value ""
tankerkoenig.0 | 2021-05-01 07:20:25.167 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.e10.3rd" has been written without ack-flag with value "0"
tankerkoenig.0 | 2021-05-01 07:20:25.167 | warn | (1843) State value to set for "tankerkoenig.0.stations.9.e10.short" has wrong type "number" but has to be "string"
tankerkoenig.0 | 2021-05-01 07:20:25.167 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.e10.short" has been written without ack-flag with value "0"
tankerkoenig.0 | 2021-05-01 07:20:25.166 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.e10.feed" has been written without ack-flag with value "0"

**Comment by SaimenSays** [comment]
Hier noch ein Link zu einem sehr interessanten Kommentar zu diesen Meldungen: https://forum.iobroker.net/post/622288

**Comment by anwa** [comment]
i have placed a Pull-request.
If someone need a quick solution, just replace the file:
/opt/iobroker/node_modules/iobroker.tankerkoenig/main.js
with the one of my pull request:
https://github.com/anwa/ioBroker.tankerkoenig/tree/jscontroller

**Comment by Pix---** [comment]
Fixed with the support of @anwa - new version is 2.0.11
